name_1="hamza"
name_2="taha"

name_3=5
name=name_1+str(name_3)
print(name)

'''hamza goes to market and then he see his friend going to market and playing his video game and going to his father hone and when he
 see his
  name of art in his '''
  #my name is hamza and i am good man
a=2.0
print(float(a))
b=3.0
d=int (b/a)
print(d)

d=b/a
print(d)
d=b//a
print(d)
d=b%a
print(d)
#some arithmatic operations
# + , - , / , *
#rule of precedence and associativity
print(3*4+4)
print(3/3*4)
print(4/1/4)
print(3*1/3)
print(3%2+3)
print(3%2)
print(3%2//1*4)
print(3/1)
print(3%2)
#divide aloways give us float value
#*always give int value
#% always give int value
#bracket power
print((3+3)/2)
print(((4)*(3+3)/2)*(3+3))
#brackets ka mamle ma sab se pehle inner brakcets solve honge phir outer brakcets

c="hamza"

print("the result is"+c)
c=1
#print("the result is"+c)#showing error becz we cant concat str with int value
#so we have to convert int to str and then concatenate
print("the result is"+str(c))
print("hello world")
_ab=1
ab_=2
print(_ab)
print(ab_)
#string oprations
string="PAkistan zIndabad love"
print(string.upper())
print(string.lower())
print(string.swapcase())
print(string.title())
print(string.capitalize())





















